package CorbaConversion;


/**
* CorbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.IDL
* lundi 27 novembre 2023 14 h 35 GMT+01:00
*/

public interface IConversionRemoteOperations 
{

  //client et serveur utilise java montant est un parametre d'entrée
  double ConversionMontant (double montant);
} // interface IConversionRemoteOperations
